global using AutoMapper;
global using CoreAppStructure.Core.Configurations;
global using CoreAppStructure.Core.Exceptions;
global using CoreAppStructure.Core.Extensions;
global using CoreAppStructure.Core.Helpers;
global using CoreAppStructure.Data;
global using CoreAppStructure.Data.Entities;
global using CoreAppStructure.Data.Models;
global using CoreAppStructure.Features.Auth.Interfaces;
global using CoreAppStructure.Features.Auth.Models;
global using CoreAppStructure.Features.Auth.Repositories;
global using CoreAppStructure.Features.Auth.Services;
global using CoreAppStructure.Features.Categories.Interfaces;
global using CoreAppStructure.Features.Categories.Models;
global using CoreAppStructure.Features.Categories.Repositories;
global using CoreAppStructure.Features.Categories.Services;
global using CoreAppStructure.Features.Parameters.Interfaces;
global using CoreAppStructure.Features.Parameters.Models;
global using CoreAppStructure.Features.Parameters.Repositories;
global using CoreAppStructure.Features.Parameters.Services;
global using CoreAppStructure.Features.Products.Interfaces;
global using CoreAppStructure.Features.Products.Mappings;
global using CoreAppStructure.Features.Products.Models;
global using CoreAppStructure.Features.Products.Repositories;
global using CoreAppStructure.Features.Products.Services;
global using CoreAppStructure.Features.Roles.Interfaces;
global using CoreAppStructure.Features.Roles.Models;
global using CoreAppStructure.Features.Roles.Repositories;
global using CoreAppStructure.Features.Roles.Servicces;
global using CoreAppStructure.Features.Users.Interfaces;
global using CoreAppStructure.Features.Users.Mappings;
global using CoreAppStructure.Features.Users.Models;
global using CoreAppStructure.Features.Users.Repositories;
global using CoreAppStructure.Features.Users.Servicces;
global using CoreAppStructure.Infrastructure.Caching;
global using CoreAppStructure.Infrastructure.Email;
global using CoreAppStructure.Infrastructure.Logging;
global using Microsoft.AspNetCore.Authentication.JwtBearer;
global using Microsoft.AspNetCore.Authorization;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.Extensions.Caching.Memory;
global using Microsoft.IdentityModel.Tokens;
global using RazorEngine;
global using RazorEngine.Templating;
global using Serilog;
global using SixLabors.ImageSharp;
global using SixLabors.ImageSharp.Formats.Webp;
global using StackExchange.Redis;
global using System.ComponentModel.DataAnnotations;
global using System.ComponentModel.DataAnnotations.Schema;
global using System.Data;
global using System.IdentityModel.Tokens.Jwt;
global using System.Net;
global using System.Net.Mail;
global using System.Security.Claims;
global using System.Security.Cryptography;
global using System.Text.Json;
global using System.Text.Json.Serialization;
global using X.PagedList;
global using DataModel = CoreAppStructure.Data.Models;
global using ILogger = Serilog.ILogger;
global using RoleModel = CoreAppStructure.Features.Roles.Models;
global using Role = CoreAppStructure.Features.Roles.Models.Role;
global using OpenTelemetry.Metrics;
global using Prometheus;
global using Metrics = Prometheus.Metrics;
global using CoreAppStructure.Infrastructure.Messaging.RabbitMQ;
global using RabbitMQ.Client;
global using Constants = CoreAppStructure.Core.Helpers.Constants;
global using Microsoft.AspNetCore.Authentication.Google;
global using Microsoft.AspNetCore.Authentication;
global using Microsoft.AspNetCore.Authentication.Cookies;
global using Microsoft.AspNetCore.Authentication.Facebook;




